//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MainGui.rc
//
#define IDD_DLG_MAIN                    101
#define IDD_DLG_PICKDLL                 102
#define IDI_ICON_SCYLLA                 103
#define IDR_MENU_DLG_MAIN               104
#define IDR_MENU_IMPORTS                105
#define IDD_DLG_DISASSEMBLER            106
#define IDR_MENU_DISASSEMBLER           107
#define IDD_DLG_ABOUT                   108
#define IDD_DLG_DONATE2                 108
#define IDD_DLG_OPTIONS                 109
#define IDR_MENU_LOG                    110
#define IDD_DLG_PICKAPI                 110
#define IDI_ICON_CHECK                  111
#define IDI_ICON_ERROR                  112
#define IDI_ICON_WARNING                113
#define IDR_ACCELERATOR_MAIN            114
#define IDD_DLG_DUMPMEMORY              115
#define IDD_DLG_DUMPSECTION             116
#define IDD_DLG_DONATE                  117
#define IDC_CBO_PROCESSLIST             1001
#define IDC_BTN_PICKDLL                 1002
#define IDC_EDIT_OEPADDRESS             1004
#define IDC_EDIT_IATADDRESS             1005
#define IDC_EDIT_IATSIZE                1006
#define IDC_BTN_IATAUTOSEARCH           1007
#define IDC_BTN_GETIMPORTS              1008
#define IDC_BTN_INVALIDIMPORTS          1009
#define IDC_BTN_SUSPECTIMPORTS          1010
#define IDC_BTN_CLEARIMPORTS            1011
#define IDC_BTN_AUTOTRACE               1012
#define IDC_BTN_DUMP                    1013
#define IDC_BTN_PEREBUILD               1015
#define IDC_BTN_CLEARLOG                1018
#define IDC_BTN_FIXDUMP                 1019
#define IDC_BTN_EXIT                    1020
#define IDC_BTN_ABOUT                   1021
#define IDC_BTN_OPTIONS                 1022
#define IDC_TREE_IMPORTS                1023
#define IDC_LIST_LOG                    1024
#define IDC_LIST_DLLSELECT              1025
#define IDC_BTN_PICKDLL_OK              1026
#define IDC_BTN_PICKDLL_CANCEL          1027
#define IDC_LIST_DISASSEMBLER           1028
#define IDC_BTN_ABOUT_OK                1029
#define IDC_STATIC_ABOUT                1030
#define IDC_OPTIONS_SECTIONNAME         1032
#define IDC_CHECK_UNLOAD_DLL            1033
#define IDC_CHECK_PE_HEADER_FROM_DISK   1034
#define IDC_BTN_OPTIONS_OK              1035
#define IDC_BTN_OPTIONS_CANCEL          1036
#define IDC_CHECK_DEBUG_PRIVILEGES      1037
#define IDC_CHECK_HEADER_CHECKSUM       1038
#define IDC_CHECK_CREATE_BACKUP         1039
#define IDC_GROUP_ATTACH                1040
#define IDC_GROUP_IMPORTS               1041
#define IDC_GROUP_IATINFO               1042
#define IDC_GROUP_LOG                   1044
#define IDC_STATIC_OEPADDRESS           1046
#define IDC_STATIC_IATADDRESS           1047
#define IDC_STATIC_IATSIZE              1048
#define IDC_STATIC_ABOUT_TITLE          1049
#define IDC_GROUP_ACTIONS               1050
#define IDC_GROUP_DUMP                  1051
#define IDC_CBO_DLLSELECT               1052
#define IDC_LIST_APISELECT              1053
#define IDC_EDIT_APIFILTER              1054
#define IDC_STATIC_APIFILTER            1055
#define IDC_GROUP_DLL                   1056
#define IDC_GROUP_APIS                  1057
#define IDC_BTN_PICKAPI_OK              1058
#define IDC_BTN_PICKAPI_CANCEL          1059
#define IDC_SYSLINK_DISTORM             1060
#define IDC_SYSLINK_WTL                 1061
#define IDC_SYSLINK_SILK                1062
#define IDC_SYSLINK_TINYXML             1063
#define IDC_SYSLINK_VISIT               1064
#define IDC_STATIC_DEVELOPED            1065
#define IDC_STATIC_YODA                 1066
#define IDC_STATIC_GREETINGS            1067
#define IDC_SYSLINK_LICENSE             1068
#define IDC_STATUS_BAR                  1069
#define IDC_LIST_DUMPMEMORY             1070
#define IDC_EDIT_DUMPADDRESS            1071
#define IDC_EDIT_DUMPSIZE               1072
#define IDC_BTN_DUMPMEMORY_OK           1073
#define IDC_BTN_DUMPMEMORY_CANCEL       1074
#define IDC_STATIC_SIZE                 1075
#define IDC_STATIC_ADDRESS              1076
#define IDC_CHECK_FORCEDUMP             1077
#define IDC_LIST_DUMPSECTION            1078
#define IDC_BTN_DUMPSECTION_OK          1079
#define IDC_BTN_DUMPSECTION_CANCEL      1080
#define IDC_BUTTON_SELECT_DESELECT      1081
#define IDC_EDIT_LISTCONTROL            1082
#define IDC_CHECK_REMOVE_DOS_STUB       1083
#define IDC_CHECK_FIX_IAT_AND_OEP       1084
#define IDC_EDIT_ADDRESS_DISASSEMBLE    1085
#define IDC_BUTTON_DISASSEMBLE          1086
#define IDC_STATIC_ADDRESS_DISASSEMBLE  1087
#define IDC_BUTTON_DISASSEMBLER_BACK    1088
#define IDC_BUTTON_DISASSEMBLER_FORWARD 1089
#define IDC_CHECK_SUSPEND_PROCESS       1090
#define IDC_CHECK1                      1091
#define IDC_CHECKOFTSUPPORT             1091
#define IDC_CHECK_USEADVANCEDIATSEARCH  1092
#define IDC_STATIC_DONATEINFO           1093
#define IDC_SCANDIRECTIMPORT            1093
#define IDC_BUTTON_COPYBTC              1094
#define IDC_NEWIATINSECTION             1094
#define IDC_FIXDIRECTIMPORTSNORMAL      1095
#define IDC_FIXDIRECTIMPORTSUNIVERSAL   1096
#define IDC_CHECKNOSECTION              1097
#define IDC_CHECK3                      1098
#define IDC_CHECKAPIALWAYSDISK          1098
#define ID_FILE_EXIT                    40001
#define ID_HELP_ABOUT                   40002
#define ID_MISC_DLLINJECTION            40003
#define ID_MISC_PREFERENCES             40004
#define ID__PLUGIN                      40005
#define ID_PLUGIN_TEST                  40006
#define ID_PLUGINS_BB                   40007
#define ID__EXPANDALLNODES              40008
#define ID__COLLAPSEALLNODES            40009
#define ID__CUTTHUNK                    40010
#define ID__DELETETREENODE              40011
#define ID__DISASSEMBLE                 40012
#define ID__INVALIDATEFUNCTION          40013
#define ID_COPYADDRESS_COPYSIZE         40014
#define ID__COPYADDRESS                 40015
#define ID__COPYSIZE                    40016
#define ID__COPYOPCODES                 40017
#define ID__COPYINSTRUCTIONS            40018
#define ID__ADDRESS                     40019
#define ID__DIS_ADDRESS                 40020
#define ID__DIS_COPYSIZE                40021
#define ID__DIS_COPYOPCODES             40022
#define ID__DIS_COPYINSTRUCTIONS        40023
#define ID__DIS_SIZE                    40024
#define ID__DIS_OPCODES                 40025
#define ID__DIS_INSTRUCTIONS            40026
#define ID_FILE_DUMP                    40029
#define ID_FILE_PEREBUILD               40030
#define ID_FILE_FIXDUMP                 40031
#define ID__CLEAR                       40033
#define ID_IMPORTS_CUTSELECTED          40041
#define ID_IMPORTS_CLEAR                40042
#define ID_IMPORTS_SHOWINVALID          40046
#define ID_IMPORTS_INVALIDATESELECTED   40048
#define ID_IMPORTS_SHOWSUSPECT          40049
#define ID_IMPORTS_CLEARIMPORTS         40050
#define ID_IMPORTS_SAVETREE             40051
#define ID_IMPORTS_LOADTREE             40052
#define ID_TRACE_AUTOTRACE              40053
#define ID__SAVE                        40054
#define ID_MISC_OPTIONS                 40055
#define ID__INVALIDATE                  40075
#define ID_FILE_DUMPMEMORY              40076
#define ID_FILE_DUMPSECTION             40077
#define ID__FGG                         40078
#define ID__FOLLOW                      40079
#define ID__DIS_FOLLOW                  40080
#define ID_MISC_DISASSEMBLER            40081
#define ID__DISASSEMBLEHERE             40082
#define ID__DIS_DISASSEMBLEHERE         40083
#define ID_HELP_DONATE                  40084

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        117
#define _APS_NEXT_COMMAND_VALUE         40085
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
